version: "3"
services:
  mongodb:
    image: mongo
    networks:
      - app-network
    logging:
      driver: none
      
  node:
    build:
      dockerfile: ./dockerfile
      context: .
    image: alexandre/node
    container_name: node
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - "mongodb"
    command: >
      sh -c "yarn seed && yarn start"

  react:
    build:
      dockerfile: ./react.dockerfile
      context: .
    image: alexandre/react
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./material:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: >
      sh -c "yarn && yarn start"
networks:
  app-network:
    driver: bridge
